-- Drops the legacy question_responses table, fully superseded by user_attempts
-- (see PRACTICE_MIGRATION_WRITEUP.md). Confirmed via information_schema/pg_catalog
-- that nothing in the live app queries this table anymore (only comments in
-- practice.repository.ts and progress.repository.ts still reference it by name),
-- and no other table holds an FK into it. Its own trigger
-- (on_question_response_insert), RLS policies (question_responses_insert_own,
-- question_responses_select_own, question_responses_select_staff), and indexes
-- are dropped automatically along with the table.
--
-- Applied directly to the live project on 2026-07-28; this file exists so the
-- migration history in source control matches what's actually live.
drop table if exists public.question_responses;
